// <auto-generated />
using Alert_to_Care;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alert_to_Care.Migrations
{
    [DbContext(typeof(ICUContext))]
    [Migration("20201008064301_InitialCreateChangeName")]
    partial class InitialCreateChangeName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");
#pragma warning restore 612, 618
        }
    }
}
